import Footer from '@/components/footer/footer'
import Navigation from '@/components/navigation/navigation'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<Navigation />
				<main className='pt-10 min-h-[calc(100vh - 300px])'>{children}</main>
				<Footer />
			</body>
		</html>
	)
}
